language: go
go_import_path: gopkg.in/bblfsh/client-go.v2

install:
  - |
    if [[ $TRAVIS_OS_NAME = linux ]]; then
      sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      sudo -E apt-get -yq update
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-6 g++-6
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
      docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/bblfshd
      docker exec -it bblfsh bblfshctl driver install python bblfsh/python-driver
    fi
  - make dependencies

script:
  - |
    if [[ $TRAVIS_OS_NAME = linux ]]; then
      make test-coverage codecov
    else
      make GO_TEST_ARGS="-v -short" test-coverage codecov
    fi

jobs:
  include:
    - {go: 1.9.x,  os: linux, sudo: required, dist: trusty, services: [docker]}
    - {go: 1.10.x, os: linux, sudo: required, dist: trusty, services: [docker]}
    - {go: 1.9.x,  os: osx, osx_image: xcode9.3}
    - {go: 1.10.x, os: osx, osx_image: xcode9.3}
